# Generated by Django 3.0.5 on 2020-07-22 07:51

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(default='2020-07-22')),
                ('phone_no', models.BigIntegerField(default=0)),
                ('email_id', models.EmailField(default='', max_length=254)),
                ('passport_num', models.BigIntegerField(default=0)),
                ('profile_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='profile_photo/profile_image.jpg', force_format=None, keep_meta=True, quality=0, size=[200, 200], upload_to='profile_photo')),
            ],
        ),
    ]
