# Generated by Django 3.0.5 on 2020-07-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='passport_num',
        ),
    ]
